Обновление обработки ответа сервера
JugglypuffM/Kotlin-Android-App pull request #14
Opened 2024-10-18 09:11 UTC by JugglypuffM

Убрал костыль с матчингом по сообщению, добавив код результата в gRPC ответ

2024-10-22 13:28 UTC, syoumzic requested changes

2024-10-22 13:28 UTC, syoumzic commented on app/src/main/kotlin/auth/GrpcAuthenticator.kt
> +            dotenv()["SERVER_ADDRESS"], dotenv()["SERVER_PORT"].toInt()
dotenv() два раза

2024-10-22 14:54 UTC, JugglypuffM commented on app/src/main/kotlin/auth/GrpcAuthenticator.kt
> +                    2 -> Result.failure(Authenticator.InvalidCredentialsException(response.message))
а зачем, эти коды не уйдут дальше обсуждаемой функции)

2024-10-22 14:58 UTC, JugglypuffM commented on app/src/main/kotlin/auth/GrpcAuthenticator.kt
> +                    2 -> Result.failure(Authenticator.InvalidCredentialsException(response.message))
я сначала думал так сделать, но потом понял что это бессмысленно, т.к. по grpc в любом случае не енам приходит, а чиселка и дополнительное отображение в енам только прибавит бессмысленной обработки, при чем именно бессмысленной, т.к. в других местах эти коды быть не должны - их единственное назначение сказать мне, какой результат операции на сервере

2024-10-24 02:55 UTC, syoumzic commented on app/src/main/kotlin/auth/GrpcAuthenticator.kt
> +                    2 -> Result.failure(Authenticator.InvalidCredentialsException(response.message))
Ок

2024-10-24 02:56 UTC, syoumzic approved these changes
Тут с самого начала request changes зря кинул, хотел просто указать

2024-10-25 07:03 UTC, AHDEPCEH approved these changes
Замечаний нет, решение с кодами ошибок считаю удачным, это к слову о комментариях Артёма

2024-10-25 07:04 UTC, merged