Добавление возможности базовой регистрации и авторизации.
JugglypuffM/Kotlin-Android-App pull request #15
Opened 2024-10-18 13:44 UTC by Jut1S

Добавление возможности базовой регистрации и авторизации. При авторизации открывается окно с данными о пользователе

2024-10-18 15:30 UTC, JugglypuffM commented on app/src/main/kotlin/KotlinAndroidApp/MainActivity.kt
> +        val registeredName = intent.getStringExtra("EXTRA_NAME")
Тут немного спорное замечание: если зарегистрироваться, залогиниться и выйти, то войти обратно ты не сможешь, потому что пока главное активити вызвано из активити регистрации, где эти экстры кладутся в интент, но после выхода главное активити вызывается из активити профиля, где этого не происходит
Это не надо фиксить, потому что когда Артем закончит свою работу этих экстр быть и не должно - данные должны будут браться с сервера

2024-10-18 15:35 UTC, JugglypuffM submitted a review, later dismissed
Все норм, можно мерджить

2024-10-24 03:55 UTC, syoumzic requested changes
Необходимо бы поменять название `MainActivity -> LoginActivity`

2024-10-24 03:55 UTC, syoumzic commented on app/src/main/kotlin/KotlinAndroidApp/RegistrationActivity.kt
> +                Toast.makeText(this, "Успешная регистрация", Toast.LENGTH_SHORT).show()
Тут уже полномочия AuthentificationWithValidation. Не критично, потом сам заменю

2024-10-25 14:05 UTC, syoumzic approved these changes

2024-10-25 14:10 UTC, JugglypuffM approved these changes

2024-10-25 14:14 UTC, merged