Объект для запроса данных пользователя
JugglypuffM/Kotlin-Android-App pull request #18
Opened 2024-10-25 07:14 UTC by JugglypuffM

Добавлен DataRequester с реализацей GrpcDataRequester, пока умеет запрашивать только имя, в прочем пока и нечего больше запросить

2024-10-27 06:00 UTC, syoumzic requested changes
Есть пару замечаний.

2024-10-27 06:00 UTC, syoumzic commented
\+ Обнови эту ветку с новой веткой `dev`, сделав `merge` или `rebase`

2024-10-27 07:44 UTC, JugglypuffM commented on app/src/main/kotlin/auth/Authenticator.kt
>  }
Надо просто переназвать, потому что если внимательно глянуть внутрь - окажется что там ничего связанного с grpc нет, это просто асинхронный вызов с обработкой

2024-10-27 07:45 UTC, JugglypuffM commented on app/src/main/kotlin/auth/GrpcAuthenticator.kt
> -     */
В коммитах указано, что я их нисколько не убрал - просто перенес в интерфейс

2024-10-27 07:48 UTC, JugglypuffM commented on app/src/main/kotlin/data/DataRequester.kt
> +                        "Failed to connect to the server: server is unavailable"
Боюсь это тебе придется)
Потому что никогда я ещё не слышал, чтобы пользователь должен был видеть ошибки....
Все эти сообщения для программистов, чтобы эти программисты потом выведи читаемое сообщение пользователю

2024-10-27 07:50 UTC, JugglypuffM commented on app/src/main/kotlin/data/GrpcDataRequester.kt
> +            dotenv()["SERVER_ADDRESS"], dotenv()["SERVER_PORT"].toInt()
Ты о чем?
Тут есть ошибка?

2024-10-27 07:57 UTC, syoumzic commented on app/src/main/kotlin/auth/Authenticator.kt
>  }
ну вообще в `authentificatorWithValidation` не нужна работа с input/output. Он лишь вызывает методы из grpc

2024-10-27 07:57 UTC, syoumzic commented on app/src/main/kotlin/auth/GrpcAuthenticator.kt
> -     */
это то я понял, я не понял почему в интерфейсе они нужны а тут нет

2024-10-27 07:57 UTC, syoumzic commented on app/src/main/kotlin/data/DataRequester.kt
> +                        "Failed to connect to the server: server is unavailable"
Тогда сообщение не имеет смысла и придётся проверять ошибки и по классу ошибки выводить сообщение. Не лучше ли сразу кидать сообщение?

2024-10-27 07:57 UTC, syoumzic commented on app/src/main/kotlin/data/GrpcDataRequester.kt
> +            dotenv()["SERVER_ADDRESS"], dotenv()["SERVER_PORT"].toInt()
нет

2024-10-27 08:00 UTC, JugglypuffM commented on app/src/main/kotlin/auth/Authenticator.kt
>  }
да, и что это меняет.....
будет потом RestAunthenticator который будет не просто оберткой как в твоем случае а реально бизнесовым классом, и там этот метод пригодится
тогда уж раз тебе это не нравится - убери наследование твоего класса с валидацией

2024-10-27 08:02 UTC, JugglypuffM commented on app/src/main/kotlin/auth/GrpcAuthenticator.kt
> -     */
пхпхпхпх, ну потому что доки вообще то из интерфейса автоматом подтягиваются....
![image](https://github.com/user-attachments/assets/e22ea4d7-e84d-4db7-8d78-0d13c77e6c8c)

2024-10-27 08:02 UTC, JugglypuffM commented on app/src/main/kotlin/data/DataRequester.kt
> +                        "Failed to connect to the server: server is unavailable"
А исключение тебе зачем выдается, Артем, хорош нести херню)

2024-10-27 08:03 UTC, syoumzic commented on app/src/main/kotlin/auth/Authenticator.kt
>  }
реализация `Authentificator` гарантирует, что в ней будут лишь `register`, `login`, а не этот метод. Так что я считаю, что лучше создать отдельный интерфейс для этого

2024-10-27 08:05 UTC, syoumzic commented on app/src/main/kotlin/data/DataRequester.kt
> +                        "Failed to connect to the server: server is unavailable"
Дак если пользователь уже есть, к примеру, то исключение не вызовется. Вернётся Result<String> и типо предлагаешь ничего не выводить?

2024-10-27 08:10 UTC, JugglypuffM commented on app/src/main/kotlin/data/DataRequester.kt
> +                        "Failed to connect to the server: server is unavailable"
о боже, ты действительно не замечаешь?
у тебя блин внутри резалта есть исключение(да он ведь на то и нужен, чтобы исключения не выбрасывать, а оборачивать и возвращать), которое ты просто вытащишь оттуда и обработаешь, оно на то и исключение, чтобы его обработал **программист**

2024-10-27 08:11 UTC, JugglypuffM commented on app/src/main/kotlin/data/DataRequester.kt
> +                        "Failed to connect to the server: server is unavailable"
исключение и не должно вызываться, оно обернуто в резалт

2024-10-27 08:15 UTC, syoumzic commented on app/src/main/kotlin/data/DataRequester.kt
> +                        "Failed to connect to the server: server is unavailable"
То есть ты утверждаешь, что сообщение необходимо для программистов, хорошо. И ты предлагаешь сообщение на сторооне ui обрабатывать, тип `is UserAlreadyExist() -> сообщенние о том, что пользователь  уже есть`, окей. Но тогда мне снова необходимо будет вернуть InvalidPassword, InvalidName, InvalidLogin чтобы более детально сообщать о том, какая именно ошибка произошла, так?

2024-10-27 08:29 UTC, JugglypuffM commented on app/src/main/kotlin/data/DataRequester.kt
> +                        "Failed to connect to the server: server is unavailable"
> Но тогда мне снова необходимо будет вернуть InvalidPassword, InvalidName, InvalidLogin чтобы более детально сообщать о том, какая именно ошибка произошла в AuthentificatorWithValidation, так?
что?

2024-10-27 08:32 UTC, JugglypuffM commented on app/src/main/kotlin/data/DataRequester.kt
> +                        "Failed to connect to the server: server is unavailable"
посмотрел твой код - все еще не понимаю о чем ты говоришь
что за InvalidPassword, InvalidName, InvalidLogin? там нет ничего подобного

2024-10-27 08:33 UTC, JugglypuffM commented on app/src/main/kotlin/data/DataRequester.kt
> +                        "Failed to connect to the server: server is unavailable"
все что тебе там надо сделать это перевести сообщения об ошибках

2024-10-27 08:35 UTC, syoumzic commented on app/src/main/kotlin/data/DataRequester.kt
> +                        "Failed to connect to the server: server is unavailable"
Смотри: Authtivicator'ы возвращают Result<String>, его необходимо обработать, однако при возврате `Result.failure(InvliadUserCredental())` не понятно что выводить: неправильный пароль, а может быть логин. Так вот я и предлагаю вернуть invalidPassword, invalidLogin, ...

2024-10-27 08:36 UTC, syoumzic commented on app/src/main/kotlin/data/DataRequester.kt
> +                        "Failed to connect to the server: server is unavailable"
это если что на будущее, что мне делать

2024-10-27 08:39 UTC, JugglypuffM commented on app/src/main/kotlin/auth/Authenticator.kt
>  }
это просто вспомогательная функция, она нужна и она специфична для каждого исполнителя запросов, поэтому ты ее не вынесешь в интерфейс - я уже попытался) гдето придестя все равно иметь функцию обработки ответа, а самый оптимальный выбор - опять же интерфейс исполнителя запросов, короче ацтань ты от нее уже, или хотя бы назови причину, по которой это плохо)

2024-10-27 08:42 UTC, JugglypuffM commented on app/src/main/kotlin/data/DataRequester.kt
> +                        "Failed to connect to the server: server is unavailable"
> не понятно что выводить: неправильный пароль, а может быть логин

так и не надо - этой ошикби(если ты все верно валидируешь) в рантайме не будет, она нужна как дополнительный уровень защиты от падения проги и в такой исключительной ситуации не грех пользователю просто вывести общее сообщение

2024-10-27 08:48 UTC, JugglypuffM commented on app/src/main/kotlin/data/DataRequester.kt
> +                        "Failed to connect to the server: server is unavailable"
даже не совсем так, данная ошибка в рантайсе будет, но там где она будет и не надо выводить конкретную информацию; я о чем: у нас будут два случая - регистрация и логин, и как раз при регистрации пользователь должен знать что он ввел не так(логин уже используется, пароль не подходит по сложности и тд), а при логине ему этого знать не просто не обязательно, даже нельзя, потому что прикинь ты ему будешь выводить сообщение о том, что пользовательне существует и он найдет таким образом существующий логин, подберет к нему пароль и залоггинится

2024-10-27 08:54 UTC, syoumzic commented on app/src/main/kotlin/auth/Authenticator.kt
>  }
Я вижу несколько исходов, которые ты предложил
1. Убрать наследование `AuthentificatonWithValidation` от `Authentificator`, тогда нарушится контракт. `AuthentificatorWithValidation` и `GrpcAuthentificator` должны иметь одни и те же поля методов `register(name, login, pass)`, `login(login, pass)`
2. Оставить данный метод в интерфейсе, но тогда нарушится логика AuthentificatorWithValidation, который не должен работать с input/output, который не умеет принимать AuthResult.  

Вывод: не отстану, иди переделывай

2024-10-27 08:54 UTC, syoumzic commented on app/src/main/kotlin/auth/Authenticator.kt
>  }
вынеси ты его в отдельный интерфейс и сделай его расширением Authentificator

2024-10-27 08:56 UTC, JugglypuffM commented on app/src/main/kotlin/auth/Authenticator.kt
>  }
Это невозможно

2024-10-27 08:56 UTC, syoumzic commented on app/src/main/kotlin/data/DataRequester.kt
> +                        "Failed to connect to the server: server is unavailable"
для регистрации то потребуется

2024-10-27 08:57 UTC, JugglypuffM commented on app/src/main/kotlin/auth/Authenticator.kt
>  }
Этот метод вообще не мешает тебе, на кой хер ты к нему прицепился

2024-10-27 08:58 UTC, syoumzic commented on app/src/main/kotlin/auth/Authenticator.kt
>  }
они мне не мешают, они мне нафиг там не сделаись

2024-10-27 08:59 UTC, syoumzic commented on app/src/main/kotlin/auth/Authenticator.kt
>  }
просто логически не понятно почему именно там он должен быть

2024-10-27 09:00 UTC, JugglypuffM commented on app/src/main/kotlin/data/DataRequester.kt
> +                        "Failed to connect to the server: server is unavailable"
А, да, я же тебе сказал удалить раздельные ошибки, нуууу, тогда возвращай))) только из уже объяви в чисто своем классе, наверное, потому что это нужно только при валидации

2024-10-27 09:02 UTC, JugglypuffM commented on app/src/main/kotlin/auth/Authenticator.kt
>  }
Потому что если пытаться сделать как ты просишь - это породит несколько почти пустых объектов назначение которых высосано из пальца

2024-10-27 09:08 UTC, syoumzic commented on app/src/main/kotlin/auth/Authenticator.kt
>  }
Структурно по мне вернее эта модель
```mermaid
graph TD;
    Authentificator -->AuthentificatorWithValidation;
    Authentificator -->IOAuthentificator
    IOAuthentificator --> GrpcAuthentificator
    IOAuthentificator --> GrpcResponse
```

нежели вот это
```mermaid
graph TD;
    IOAuthentificator -->AuthentificatorWithValidation;
    IOAuthentificator --> GrpcAuthentificator
    IOAuthentificator --> GrpcResponse
```
где AuthentificatorWithValidation делает то, что ему делать не надо (input/output)

2024-10-27 09:10 UTC, JugglypuffM commented on app/src/main/kotlin/auth/Authenticator.kt
>  }
а по мне вернее модель где аутентификатор занимается аутентификацией, а не валидацией)

2024-10-27 09:19 UTC, JugglypuffM commented on app/src/main/kotlin/auth/Authenticator.kt
>  }
> где AuthentificatorWithValidation делает то, что ему делать не надо (input/output)

странный ты...
ты взял мой класс, начал его расширять и теперь жалуешься что в нем есть методы которыми ты не пользуешься - так твоя задача это блин расширять, какая тебе нахер разница какие внутри есть методы
короче Артем, ты однозначно в данной ситуации не прав, верное решение в данном случае - ничего не менять

2024-10-27 09:21 UTC, syoumzic commented on app/src/main/kotlin/auth/Authenticator.kt
>  }
AuthentificatironVithValidaion уже утверждён и в dev, а ты предлагаешь его упрознить в этом pr, что не есть круто, совсем не круто

2024-10-27 09:30 UTC, JugglypuffM commented on app/src/main/kotlin/auth/Authenticator.kt
>  }
по факту это твоя проблема - тебе не нравится, что у тебя при расширении другого класса используются не все методы этого класса
ну это же глупо: не надо - так не пользуйся)

2024-10-27 09:44 UTC, syoumzic commented on app/src/main/kotlin/auth/Authenticator.kt
>  }
> странный ты...
> ты взял мой класс, начал его расширять и теперь жалуешься что в нем есть методы которыми ты не пользуешься - так твоя задача это блин расширять, какая тебе нахер разница какие внутри есть методы
> короче Артем, ты однозначно в данной ситуации не прав, верное решение в данном случае - ничего не менять

мы говорим об архитектуре в целом, а не то что ты создал, а я от него наследовался. тут уже целая картина вырисовалась о назначении Authentificator, которое у нас разное

2024-10-27 09:46 UTC, syoumzic commented on app/src/main/kotlin/auth/Authenticator.kt
>  }
пофиг, что они не используютя. Логически неправильная схема меня не устраивает

2024-10-27 09:48 UTC, syoumzic commented on app/src/main/kotlin/auth/Authenticator.kt
>  }
> какая тебе нахер разница какие внутри есть методы

ты меняешь контракт не только для  своих классов, но и для моего

2024-10-27 09:49 UTC, JugglypuffM commented on app/src/main/kotlin/auth/Authenticator.kt
>  }
> Логически неправильная схема сущностей приожения

До нынешнего момента ты не этим аргументировал свои претензии)
А так я правки уже внёс и с конкретно данным утверждением согласен

2024-10-27 09:49 UTC, syoumzic commented on app/src/main/kotlin/auth/Authenticator.kt
>  }
это как заставить рыб летать, просто потому что появился класс птица

2024-10-27 09:50 UTC, JugglypuffM commented on app/src/main/kotlin/auth/Authenticator.kt
>  }
Ты продолжаешь закапывать себя глубже - это твое решение унаследовать рыбу от птицы)

2024-10-27 09:50 UTC, syoumzic commented on app/src/main/kotlin/data/DataRequester.kt
> +                        "Failed to connect to the server: server is unavailable"
ок

2024-10-27 09:52 UTC, syoumzic commented on app/src/main/kotlin/auth/Authenticator.kt
>  }
нет, это как раз ты подписал рыб на полёт, вместо того, чтобы создать интерфейс для летающих

2024-10-27 09:54 UTC, syoumzic requested changes
обнови ветку сделав `rebase` или `merge` от текущей dev? чтобы при merge после pr ничего не сломать

2024-10-27 09:55 UTC, JugglypuffM commented on app/src/main/kotlin/auth/Authenticator.kt
>  }
Артем, хорош усугублять - иди смотри изменения и резолви

2024-10-27 09:56 UTC, JugglypuffM commented
Мне не позволяет ничего сломать, потом если изменения будут нужны смерджу

2024-10-27 09:56 UTC, syoumzic commented on app/src/main/kotlin/auth/Authenticator.kt
>  }
ладно, ладно, всё

2024-10-27 09:58 UTC, syoumzic commented
что ты имеешь в виду?

2024-10-27 10:38 UTC, JugglypuffM commented
Ответ на твой вопрос...
Типа если нельзя будет безопасно смерджить автоматически, то сделаю это вручную

2024-10-27 10:51 UTC, AHDEPCEH approved these changes

2024-10-27 11:10 UTC, AHDEPCEH commented
Короче, я прочитал, ваши обсуждения, изменения принял. По поводу замечания по интерфейсу от Артёма, там соглашусь, что не стоило пихать туда метод, который сузит интерфейс, когда от него этого не ждут. Хорошо, что его вынесли. По Поводу ошибок на русском языке - это вообще дикость, Тёма, запомни, использовать в принципе русский язык в коде - дурная затея, не считая документации. И то было бы хорошим тоном писать её на английском, но я не думаю, что нам доведётся продвигать проект куда-то далеко, поэтому так будет удобнее для нас самих.

2024-10-27 11:12 UTC, syoumzic commented
Если делать так Стас мне объяснил, то да... Согласен

2024-10-28 08:51 UTC, syoumzic approved these changes
Ну можно и вручную. Всё равно там есть ci

2024-10-28 08:51 UTC, syoumzic commented
Мердж

2024-10-28 09:04 UTC, merged