Класс аутентификатор для отправки запросов на сервер по gRPC
JugglypuffM/Kotlin-Android-App pull request #2
Opened 2024-10-10 23:14 UTC by JugglypuffM

теперь наконецто на грэйдле, сколько же я с ним намучился
если есть какието вопросы по нему - тоже задавайте

2024-10-12 10:36 UTC, syoumzic reviewed
В целом ок, только тест не запускается.

2024-10-12 10:36 UTC, syoumzic commented on app/src/main/kotlin/TestGRPC.kt
для чего этот файл, если есть AuthenticatorTest.kt?

2024-10-12 10:36 UTC, syoumzic commented on app/src/test/kotlin/auth/AuthenticatorTest.kt
Есть нюанс связанный с тестом: он не запускается (не видит либ mock, jupiter)

2024-10-12 10:58 UTC, syoumzic commented on app/src/main/kotlin/domain/AuthResult.kt
> +)
можно разделить на Auth.Sucess, Auth.Dismiss

```
sealed class Auth{
    data class Sucess(val message: String): Auth()
    data class Dismiss(val message: String): Auth()
}
```

что бы потом проверять результат так
```
when(result){
   is Auth.Sucess -> ...
   is Auth.Dismiss -> ...
}
```

а не так
```
if(result.sucess) ...
else ...

2024-10-12 11:30 UTC, JugglypuffM commented on app/src/test/kotlin/auth/AuthenticatorTest.kt
Эту проблему я уже решил - юпитер просто не работает, знайте
Просто потом оказалось, что сами тесты говно, теперь переписываю

2024-10-12 11:33 UTC, JugglypuffM commented on app/src/main/kotlin/TestGRPC.kt
В целом можно будет удалить, когда удостоверюсь в качестве тестов, но вообще этот файл нужен для проверки на работоспособность системы в сумме

2024-10-12 11:33 UTC, JugglypuffM commented on app/src/main/kotlin/domain/AuthResult.kt
> +)
Отличная идея, так и сделаю!

2024-10-12 11:33 UTC, JugglypuffM commented
Киньте кто-нибудь request changes

2024-10-12 16:37 UTC, syoumzic commented on app/src/main/kotlin/auth/Authenticator.kt
> +class Authenticator(private val address: String, private val port: Int) {
Можно упростить для использования использование извне
``` suggestion
object Authenticator(){
   private val adress: String = ..
   private val port: Int = ..
```

2024-10-12 16:43 UTC, JugglypuffM commented on app/src/main/kotlin/auth/Authenticator.kt
> +class Authenticator(private val address: String, private val port: Int) {
Что-то я вообще не понял смысла, объясни подробнее)

2024-10-12 16:53 UTC, syoumzic commented on app/src/main/kotlin/auth/Authenticator.kt
> +class Authenticator(private val address: String, private val port: Int) {
Я предлагаю заменить `class` на `object`, что бы использовать Authenticator без инициализации
```
Authenticator.registry(name, login, pass)
```
вместо
```
val auth: Authenticator = Authenticator(ip, port)
auth.registry(name, login, pass)
```
\+ это скрывает внутренюю реализацию (не нужно явно указывать адрес, порт сервера)

2024-10-12 16:54 UTC, JugglypuffM commented on app/src/main/kotlin/auth/Authenticator.kt
> +class Authenticator(private val address: String, private val port: Int) {
А адрес сервера куда в таком случае?

2024-10-12 16:55 UTC, syoumzic commented on app/src/main/kotlin/auth/Authenticator.kt
> +class Authenticator(private val address: String, private val port: Int) {
внутрь класса final переменной

2024-10-12 16:57 UTC, JugglypuffM commented on app/src/main/kotlin/auth/Authenticator.kt
> +class Authenticator(private val address: String, private val port: Int) {
Вообще не варик: а если мы захотим масштабировать я, да даже банально адрес у сервера поменяется

2024-10-12 17:00 UTC, syoumzic commented on app/src/main/kotlin/auth/Authenticator.kt
> +class Authenticator(private val address: String, private val port: Int) {
Я тебя понял.
Тогда оставляем.

2024-10-13 09:01 UTC, syoumzic commented on app/src/test/kotlin/auth/AuthenticatorTest.kt
а как решил?

2024-10-13 09:01 UTC, JugglypuffM commented on app/src/test/kotlin/auth/AuthenticatorTest.kt
Ну, достаточно прозаично - использовал простой junit)))

2024-10-13 09:02 UTC, JugglypuffM commented on app/src/main/kotlin/TestGRPC.kt
Провер очка

2024-10-13 09:02 UTC, syoumzic requested changes
тесты допилить и всё ок

2024-10-13 09:03 UTC, syoumzic commented on app/src/test/kotlin/auth/AuthenticatorTest.kt
дак ты ж ничего не менял
а тесты так и не запускаются

2024-10-13 09:05 UTC, JugglypuffM commented on app/src/test/kotlin/auth/AuthenticatorTest.kt
Я пока не закоммитил ничего с тех пор, на компе у меня все запускается, просто сами тесты говно и я их ещё не сел переписывать - в падлу
Я вообще то и так всю неделю ебашил)))

2024-10-13 09:07 UTC, syoumzic commented on app/src/test/kotlin/auth/AuthenticatorTest.kt
пон

2024-10-13 14:02 UTC, JugglypuffM commented on app/src/main/kotlin/domain/AuthResult.kt
> +)
Нашел класс Result<T> который делает буквально то же самое, только в failure находиться ошибка, что делает обработку несколько проще

2024-10-13 14:02 UTC, JugglypuffM commented on app/src/test/kotlin/auth/AuthenticatorTest.kt
теперь тестам хорошо, они нормовые

2024-10-13 16:00 UTC, syoumzic reviewed
ок

2024-10-13 16:05 UTC, syoumzic approved these changes

2024-10-13 16:06 UTC, merged