Добавлена доменная модель для тренировок
JugglypuffM/Kotlin-Android-App pull request #23
Opened 2024-11-11 10:44 UTC by syoumzic

Добавлена доменная модель достаточная для проведения тренировок и их учёта

2024-11-22 08:21 UTC, AHDEPCEH requested changes
Добавить мне больше нечего, по поводу комментариев Стаса согласен

2024-11-22 08:21 UTC, AHDEPCEH commented on app/src/main/kotlin/domain/training/TrainingEntity.kt
Ещё хотелось бы добавить расстояние или пройденную дистанцию

2024-11-22 08:54 UTC, JugglypuffM requested changes
Еще вопросеки

2024-11-22 09:02 UTC, syoumzic commented on app/src/main/kotlin/auth/GrpcAuthenticator.kt
убрал

2024-11-22 09:02 UTC, syoumzic commented on app/src/main/kotlin/data/GrpcDataRequester.kt
убрал

2024-11-22 10:50 UTC, JugglypuffM requested changes

2024-11-22 10:50 UTC, JugglypuffM commented on app/src/main/kotlin/domain/training/trainings/Jogging.kt
> +class Jogging(private val distance: Double): TrainingInfo {
Это снова противоречит замечанию из первой пачки: раз ты сделал не тип, а класс, то уж и храни все тренировки в таких классах, то есть: сделай интерфейс который объединит интерфейсы TrainingEntity и Training info, назови его условно просто Training и храни список тренировок как List[Training], где всякие Jogging, Yoga и прочие просто реализуют интерфейс

2024-11-23 13:53 UTC, JugglypuffM approved these changes
Вот это уже выглядит хорошо

2024-11-27 10:41 UTC, AHDEPCEH approved these changes
Замечаний нет, мёрджить, странный конечно выбор упражнения - ёга, ну ладно.

2024-11-27 10:41 UTC, merged