Domain change
JugglypuffM/Kotlin-Android-App pull request #25
Opened 2024-11-28 04:12 UTC by syoumzic

2024-11-28 06:40 UTC, JugglypuffM requested changes
Несколько мелочей

2024-11-28 06:40 UTC, JugglypuffM commented on app/src/main/kotlin/utils/Validator.kt
>      }
Тут имя забыл убрать

2024-11-28 12:19 UTC, syoumzic commented on app/src/main/kotlin/auth/GrpcAuthenticator.kt
>   */
не совсем понимаю, что должно в доке поменяться.

2024-11-28 12:19 UTC, syoumzic commented on app/src/main/kotlin/auth/GrpcAuthenticator.kt
>   */
добавил doc для конструкторов

2024-11-29 09:41 UTC, JugglypuffM approved these changes

2024-12-06 15:06 UTC, Jut1S approved these changes
гуд

2024-12-06 16:20 UTC, merged