Добавление: Экран авторизации
JugglypuffM/Kotlin-Android-App pull request #3
Opened 2024-10-13 06:31 UTC by Jut1S

2024-10-13 06:50 UTC, syoumzic reviewed
Всё ок. Жду окна регистрации

2024-10-13 07:16 UTC, syoumzic commented
Переименуй директорию java на kotlin (app/src/java -> app/src/kotlin)

2024-10-13 08:49 UTC, JugglypuffM requested changes
Выглядит норм, переименуй, как Артем сказал и можно мерджить

2024-10-15 09:20 UTC, JugglypuffM commented
Надо же ещё окно регистрации добавить: как это сделать - на твое усмотрение: либо по умолчанию открывать окно логина, и снизу кнопка для перехода к регистрации, либо наоборот, либо вообще изначально две кнопки - логин или регистрация

2024-10-15 10:19 UTC, syoumzic commented
Можешь избавиться от директорий com\example\KotlinAndroidApp

2024-10-15 11:48 UTC, Jut1S commented
> Переименуй директорию java на kotlin (app/src/java -> app/src/kotlin)

Переименовал. В пакете переименовал так же example на project, оставим в таком формате, это самый оптимальный выбор

2024-10-15 11:52 UTC, syoumzic commented
да я не про название пакета писал
у тебя директории kotlin/com/project/KotlinAndroidApp/AndroidActivity.kt, а надо kotlin/AndroidActivity.kt

2024-10-15 12:57 UTC, JugglypuffM commented
@syoumzic, то что он сделал - ты тоже просил)
так что все правильно, @Jut1S

2024-10-15 13:01 UTC, JugglypuffM commented on app/build.gradle.kts
> +    namespace = "com.project.kotlin_android_app"
артем предложил полностью убрать com.example, а не заменить

2024-10-15 13:01 UTC, JugglypuffM commented on app/build.gradle.kts
> +        applicationId = "com.project.kotlin_android_app"
и здесь тоже

2024-10-15 13:02 UTC, JugglypuffM commented
зачем вообще нужны namespace и applicationId?

2024-10-17 12:34 UTC, JugglypuffM reviewed
вопрос остался

2024-10-17 12:35 UTC, JugglypuffM commented on app/build.gradle.kts
> +    namespace = "com.project.kotlin_android_app"
я все еще не понимаю зачем они нужны)

2024-10-17 12:55 UTC, Jut1S commented on app/build.gradle.kts
> +    namespace = "com.project.kotlin_android_app"
Не работает если их удалить

2024-10-17 20:41 UTC, JugglypuffM submitted a review, later dismissed
В принципе можно мерджить

2024-10-18 04:47 UTC, syoumzic approved these changes

2024-10-18 04:47 UTC, merged