написание класса для валидации данных регистрации/авторизации
JugglypuffM/Kotlin-Android-App pull request #6
Opened 2024-10-15 20:51 UTC by syoumzic

2024-10-15 21:29 UTC, JugglypuffM requested changes
Есть пара проблем и немного больше, чем пара, вопросов

2024-10-15 21:29 UTC, JugglypuffM commented on app/src/main/kotlin/auth/AuthenticatorManager.kt
> +        }
Это что за шутка юмора?)

2024-10-15 21:29 UTC, JugglypuffM commented on app/src/main/kotlin/auth/AuthenticatorManager.kt
> +        if (password.length <= 5) {
Небольшая несостыковочка вышла, на сервере <=6

2024-10-15 21:29 UTC, JugglypuffM commented on app/src/main/kotlin/auth/AuthenticatorManager.kt
> +            return Result.failure(Exception("Имя пользователя пустое"))
Здесь и далее: возвращать безымянное исключение может быть не самым лучшим решением, вдруг потом нужно будет различать ситуации падения.
Я бы лучше создал пару исключений.

2024-10-15 21:29 UTC, JugglypuffM commented on app/src/main/kotlin/auth/AuthenticatorManager.kt
> + *
Блин, я вот не придал значения тогда, но его ведь и правда его лучше назвать AuthenticationManager, а то и слух режет и неправильно: это же мэнэджер аутентификации, а не аутентификаторов, который вообще должен быть один
Короче переименуй пжшка
И тесты переименовать не забудь)

2024-10-15 21:29 UTC, JugglypuffM commented on app/src/main/kotlin/auth/AuthenticatorManager.kt
> + * Синтаксис для валидации данных регистрации/авторизации
Что значит слово синтаксис?
Типа скалиста из себя строишь даааа?))))
Если да, то в котлине это фактически неприменимо, ибо синтаксис для T, значит, что посредством тайпклкссов и имплиситов у тебя к стандартному типу добавляется ad-hoc функциональность, т.е. тебе не приходится инстанс чего-нибудь другого создавать, как в случае с этим классом
А если не строишь, то я теряюсь в догадках, что это значит)

2024-10-15 21:29 UTC, JugglypuffM commented on app/src/main/kotlin/auth/AuthenticatorManager.kt
> + * Является обёрткой над Authenticator @see Authenticator
Раз он является обёрткой, то почему бы не унаследовать его от GrpcAuthenticator?
Не то чтобы это жесть какая крутая и полезная идея, просто почему бы так не сделать?)
Зато в будущем может помочь при написании полиморфного кода

2024-10-15 21:29 UTC, JugglypuffM commented on app/src/main/kotlin/auth/AuthenticatorManager.kt
> +     * Функция авторизации пользователя
Не совсем замечание, скорее вопрос: выглядит очень громоздко и очень похоже на дешугаренный for-comprehension из скалы, а раз Котлин это почти скала, то может и в нем есть какойнибудь сахар на такой случай?

2024-10-17 12:08 UTC, JugglypuffM commented on app/src/main/kotlin/auth/AuthenticatorManager.kt
> + * Синтаксис для валидации данных регистрации/авторизации
Ничем из этого понятие синтаксис не является, выбери что-нибудь одно)

2024-10-17 14:16 UTC, syoumzic commented on app/src/main/kotlin/auth/AuthenticatorManager.kt
> + * Является обёрткой над Authenticator @see Authenticator
В принципе идея не плохая даже с точки зрения того, что в классе валидации и в grpc отправке должны быть один и те же методы, но не исключения

2024-10-17 18:35 UTC, syoumzic commented on app/src/main/kotlin/auth/AuthenticatorManager.kt
> +     * Функция авторизации пользователя
К сожалению, это максимум, что я выжал из kotlin`a.
Там из фп только fold да map у объектов

2024-10-17 19:10 UTC, syoumzic commented
вроде всё исправил

2024-10-17 20:06 UTC, JugglypuffM requested changes
Подправить пару мелочей

2024-10-17 20:06 UTC, JugglypuffM commented on app/src/main/kotlin/auth/AuthenticationManager.kt
> +class AuthenticationManager(private val authenticator: Authenticator = GrpcAuthenticator()): Authenticator{
Тут вынужден извиниться за ветреность, но попрошу поменять название на AuthenticatorWithValidation, потому что в таком случае название класса будет идеально соответствовать сути
А ещё убери значение по умолчанию: не особо очевидна причина, по которой именно gRPC реализация является стандартной, а значение по умолчанию подразумевает как раз какое-то самое базовое и простое решение
Выглядит как доебы с воздуха, но мне кажется, что эти мелочи достаточно надоедливые и несколько портят понятность кода

2024-10-18 04:58 UTC, syoumzic commented on app/src/main/kotlin/auth/AuthenticationManager.kt
> +        if (password.length <= 6) {
my - bad, я тоже после того как код сервера посмотрел запутался

2024-10-18 05:02 UTC, syoumzic commented on app/src/main/kotlin/auth/AuthenticationManager.kt
> +class AuthenticationManager(private val authenticator: Authenticator = GrpcAuthenticator()): Authenticator{
по поводу названия согласен, по поводу дефолтного значения - нет
во-первых это добавляет мобильности. Если вдруг что-либо появится (какой нибудь HTMLAuthentificator), то его можно будет безболезненно поменять
во-вторых, а как в тестах тогда его мокать, через setAuthentificator - не красиво

2024-10-18 05:02 UTC, syoumzic commented on app/src/main/kotlin/auth/Authenticator.kt
> +    class IncorrectPasswordException(message: String): Exception(message)
что grpcAuthentificator, что AuthentificatonManager реализуют интерфейс Authentificator. И ошибки там должны по мне быть все. Если уж и выносить их то выносить все, что не очень структурировано. Лучше их в одном месте хранить

2024-10-18 05:08 UTC, JugglypuffM commented on app/src/main/kotlin/auth/AuthenticationManager.kt
> +class AuthenticationManager(private val authenticator: Authenticator = GrpcAuthenticator()): Authenticator{
Да я не предлагаю параметр убрать, я хочу чтобы дефолтной реализацией не был GrpcAuthenticator, потому что это не имеет причины под собой

2024-10-18 05:10 UTC, JugglypuffM commented on app/src/main/kotlin/auth/Authenticator.kt
> +    class IncorrectPasswordException(message: String): Exception(message)
Кстати, что-то я не заметил во-первых, что я сам это начал, а во-вторых, что ты одно из моих исключений продублировал и разделил на два: Invalid credentials это и есть неверный логин или пароль, его и возвращай

2024-10-18 05:14 UTC, JugglypuffM commented on app/src/main/kotlin/auth/AuthenticationManager.kt
> +}
Вообще только что подумал, как жёстко ты надругался над ооп, которое постулирует одну задачу у каждого объекта
А тут он у тебя и валидирует и аутентифицирует
Такой подход, который ты использовал это скорее тема фп, которое в нашем случае не то чтобы имеет место
Мне кажется вообще имеет смысл выделить логику валидации в отдельный класс и потом в коде сначала валидирлвать данные, а потом отправлять запрос

2024-10-18 05:31 UTC, JugglypuffM commented on app/src/main/kotlin/auth/AuthenticationManager.kt
> +}
Вообще я так подумал - ничего против такого решения не имею
Забавно, как быстро мы положили на принципы ооп)

2024-10-22 10:29 UTC, syoumzic commented on app/src/main/kotlin/auth/AuthenticationManager.kt
> +}
Никакие принципы ооп тут не нарушены. Это просто удобная обёртка для простоты написания кода. На самом деле мой класс не регистрирует и не авторизовывает пользователей. Этим занимается GRPCAuthentificator. Класс AuthentificatorWithValidate лишь использует его

2024-10-22 13:40 UTC, syoumzic commented on app/src/main/kotlin/auth/AuthenticationManager.kt
> +class AuthenticationManager(private val authenticator: Authenticator = GrpcAuthenticator()): Authenticator{
Я уже писал, что не знаю как иначе это реализовывать. Что такого если выбор authentificator внутри делать.

2024-10-23 14:43 UTC, syoumzic commented
исправил. Долбанный гит. Ещё позавчера думал, что изменения залил

2024-10-23 16:34 UTC, JugglypuffM requested changes
Чтото странное произошло, плюс есть пара вопросов

2024-10-23 16:34 UTC, JugglypuffM commented on app/src/main/kotlin/auth/GrpcAuthenticator.kt
> +     * @param password пароль новой учетной записи - строка длиннее 6и символов
Это как вообще понимать?
Зачем лезть в чужой код?

2024-10-23 16:34 UTC, JugglypuffM commented on app/src/main/kotlin/auth/Auth.kt
> +object Auth: Authenticator by AuthenticationWithValidation(GrpcAuthenticator())
Зачем это?

2024-10-23 16:34 UTC, JugglypuffM commented on app/src/main/kotlin/auth/AuthenticationManager.kt
> +        if (password.length <= 6) {
Тут пропустил)

2024-10-23 16:34 UTC, JugglypuffM commented on app/src/main/kotlin/auth/AuthenticationWithValidation.kt
> +class AuthenticationWithValidation(private val authenticator: Authenticator = GrpcAuthenticator()): Authenticator{
Чтото странное произошло кажется...
Копировал классы? Зачем?

2024-10-23 16:34 UTC, JugglypuffM commented on app/src/main/kotlin/auth/AuthenticationWithValidation.kt
> +class AuthenticationWithValidation(private val authenticator: Authenticator = GrpcAuthenticator()): Authenticator{
А, здесь, смотрю, исправлена проверка длинны пароля

2024-10-23 16:34 UTC, JugglypuffM commented on app/src/main/kotlin/auth/AuthenticationWithValidation.kt
> +class AuthenticationWithValidation(private val authenticator: Authenticator = GrpcAuthenticator()): Authenticator{
Но зачем оставил AuthenticationManager?

2024-10-23 16:34 UTC, JugglypuffM commented on app/src/main/kotlin/auth/AuthenticationManager.kt
> +        if (password.length <= 6) {
А, исправлено в другом месте...

2024-10-23 16:34 UTC, JugglypuffM commented on app/src/test/kotlin/auth/AuthenticationManagerTest.kt
> +class AuthenticationManagerTest {
Аналогично: зачем два одинаковых класса с двумя одинаковыми тестами?

2024-10-23 17:22 UTC, syoumzic commented on app/src/main/kotlin/auth/Auth.kt
> +object Auth: Authenticator by AuthenticationWithValidation(GrpcAuthenticator())
это было для того что бы потом Никите с нескольким страницами было удобно пользоваться, однако я так подумал, что там дальше (на его стороне) потребуется какой-нибудь uiAuthentificator, так что решил убрать

2024-10-23 17:22 UTC, syoumzic commented on app/src/main/kotlin/auth/AuthenticationManager.kt
> +        if (password.length <= 6) {
удалил AuthentificatonManager, все изменения теперь в AuthentificatorWithValidation

2024-10-23 17:22 UTC, syoumzic commented on app/src/main/kotlin/auth/AuthenticationWithValidation.kt
> +class AuthenticationWithValidation(private val authenticator: Authenticator = GrpcAuthenticator()): Authenticator{
Какая то не разбериха у меня с гитом вышла: был рефакторинг `AuthentificatorManager -> AuthentificatorWithValidation`. Старая версия слилась с новой и вот. Теперь всё ок

2024-10-23 17:22 UTC, syoumzic commented on app/src/main/kotlin/auth/GrpcAuthenticator.kt
> +     * @param password пароль новой учетной записи - строка длиннее 6и символов
понял, зря быканул

2024-10-23 17:22 UTC, JugglypuffM submitted a review, later dismissed
Все норм, можно мерджить, кажется

2024-10-25 06:18 UTC, JugglypuffM approved these changes

2024-10-25 06:22 UTC, merged